
%token KPROGRAM
%token IDENTIFIER
%token LPAREN RPAREN
%token SEMICOLON COLON DOT COMMA
%token KVAR
%token KARRAY
%token LBRAC RBRAC
%token NUM
%token KSTRING
%token STRINGCONST
%token KOF
%token KINTEGER
%token KREAL
%token KFUNCTION
%token KPROCEDURE
%token KBEGIN KEND
%token ASSIGNMENT
%token KIF KTHEN KELSE
%token KWHILE KDO
%token LESS GREATER LESSEQUAL GREATEREQUAL EQUAL NOTEQUAL
%token PLUS MINUS
%token STAR SLASH
%token KNOT DOTDOT
%token KAND KOR

%%

program: ;

%%